service:
  name: brokerage-service

plugins:
  - serverless-webpack
  - serverless-pseudo-parameters
  - serverless-domain-manager
  - serverless-api-gateway-caching

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: us-east-2
  environment:
    REGION: ${self:provider.region}
    ENVIRONMENT: ${self:provider.stage}
functions:
  createBrokerage:
    handler: src/handlers/createBrokerage.handler
    events:
      - http:
          method: POST
          path: /brokerage
  getBrokerages:
    handler: src/handlers/getBrokerages.handler
    events:
      - http:
          method: GET
          path: /brokerages
  getBrokerage:
    handler: src/handlers/getBrokerage.handler
    events:
      - http:
          method: GET
          path: /brokerage/{id}
  updateBrokerageSeat:
    handler: src/handlers/updateBrokerageSeat.handler
    events:
      - http:
          method: PATCH
          path: /brokerage/{id}/seat/{seatCount}
custom:
  # Enable or disable caching globally
  apiGatewayCaching:
    enabled: false
    clusterSize: '0.5' # defaults to '0.5'
    ttlInSeconds: 300 # defaults to the maximum allowed: 3600
    dataEncrypted: true # defaults to false
    perKeyInvalidation:
      requireAuthorization: true # default is true
      handleUnauthorizedRequests: Ignore # default is "IgnoreWithWarning".
