service:
  name: agent-client-service

plugins:
  - serverless-webpack
  - serverless-pseudo-parameters
  - serverless-domain-manager
  - serverless-api-gateway-caching

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: us-east-2
  environment:
    REGION: ${self:provider.region}
    ENVIRONMENT: ${self:provider.stage}
functions:
  addClient:
    handler: src/handlers/addClient.handler
    events:
      - http:
          method: POST
          path: /agent/client/{id}
  getAgentClients:
    handler: src/handlers/getAgentClients.handler
    events:
      - http:
          method: GET
          path: /agent/{id}/clients
custom:
  # custom domain
  customDomain:
    domainName: ${self:provider.stage}.kioskify.ca
    basePath: client-agent
    stage: ${self:provider.stage}
    createRoute53Record: true
  # Enable or disable caching globally
  apiGatewayCaching:
    enabled: false
    clusterSize: '0.5' # defaults to '0.5'
    ttlInSeconds: 300 # defaults to the maximum allowed: 3600
    dataEncrypted: true # defaults to false
    perKeyInvalidation:
      requireAuthorization: true # default is true
      handleUnauthorizedRequests: Ignore # default is "IgnoreWithWarning".
