service:
  name: agent-service

plugins:
  - serverless-pseudo-parameters
  - serverless-domain-manager
  - serverless-api-gateway-caching
  - serverless-offline
  - serverless-plugin-typescript
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: us-east-2
  environment:
    REGION: ${self:provider.region}
    ENVIRONMENT: ${self:provider.stage}

functions:
  createAgent:
    handler: src/handlers/createAgent.handler
    events:
      - http:
          method: POST
          path: /agent
          authorizer: ${self:custom.authorizer}
  getAgents:
    handler: src/handlers/getAgents.handler
    events:
      - http:
          method: GET
          path: /
          authorizer: ${self:custom.authorizer}
          caching:
            enabled: false
  getAgent:
    handler: src/handlers/getAgent.handler
    events:
      - http:
          method: GET
          path: /agent/{id}
          authorizer: ${self:custom.authorizer}
          caching:
            enabled: false
            cacheKeyParameters:
              - name: request.path.id
              - name: request.header.Accept-Languag
  getAgentsByBrokerage:
    handler: src/handlers/getAgentsByBrokerage.handler
    events:
      - http:
          method: GET
          path: /brokerage/{id}
          authorizer: ${self:custom.authorizer}
  updateAgentStatus:
    handler: src/handlers/updateAgentStatus.handler
    events:
      - http:
          method: PATCH
          path: /{id}/activityStatus/{activityStatus}
          authorizer: ${self:custom.authorizer}
  updateAgentPlan:
    handler: src/handlers/updateAgentPlan.handler
    events:
      - http:
          method: PATCH
          path: /{id}/planType/{planType}
          authorizer: ${self:custom.authorizer}

custom:
  authorizer: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:auth-service-${self:provider.region}-auth
  # custom domain
  customDomain:
    domainName: kioskify.ca
    basePath: agents
    stage: ${self:provider.stage}
    createRoute53Record: true
  # Enable or disable caching globally
  apiGatewayCaching:
    enabled: false
    clusterSize: '0.5' # defaults to '0.5'
    ttlInSeconds: 300 # defaults to the maximum allowed: 3600
    dataEncrypted: true # defaults to false
    perKeyInvalidation:
      requireAuthorization: true # default is true
      handleUnauthorizedRequests: Ignore # default is "IgnoreWithWarning".
