service:
  name: agent-service

plugins:
  - serverless-webpack
  - serverless-pseudo-parameters
  - serverless-domain-manager
  - serverless-api-gateway-caching

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: us-east-2
  environment:
    REGION: ${self:provider.region}
    ENVIRONMENT: ${self:provider.stage}

functions:
  createAgent:
    handler: src/handlers/createAgent.handler
    events:
      - http:
          method: POST
          path: /agent
  getAgents:
    handler: src/handlers/getAgents.handler
    events:
      - http:
          method: GET
          path: /agents
          caching:
            enabled: false
  getAgent:
    handler: src/handlers/getAgent.handler
    events:
      - http:
          method: GET
          path: /agent/{id}
          caching:
            enabled: false
            cacheKeyParameters:
              - name: request.path.id
              - name: request.header.Accept-Languag
  getAgentByBrokerage:
    handler: src/handlers/getAgentByBrokerage.handler
    events:
      - http:
          method: GET
          path: /agent/brokerage/{id}
  updateAgentStatus:
    handler: src/handlers/updateAgentStatus.handler
    events:
      - http:
          method: PATCH
          path: /agent/{id}/activityStatus/{activityStatus}

  updateAgentPlan:
    handler: src/handlers/updateAgentPlan.handler
    events:
      - http:
          method: PATCH
          path: /agent/{id}/planType/{planType}

custom:
  # custom domain
  customDomain:
    domainName: kioskify.ca
    basePath: '/'
    stage: ${self:provider.stage}
    createRoute53Record: true
  # Enable or disable caching globally
  apiGatewayCaching:
    enabled: false
    clusterSize: '0.5' # defaults to '0.5'
    ttlInSeconds: 300 # defaults to the maximum allowed: 3600
    dataEncrypted: true # defaults to false
    perKeyInvalidation:
      requireAuthorization: true # default is true
      handleUnauthorizedRequests: Ignore # default is "IgnoreWithWarning".
